<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>Meya.Desktop</AssemblyName>
    <RootNamespace>Meya.Desktop</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
    <ProjectReference Include="..\Meya.Core\Meya.Core.csproj" />
    <ProjectReference Include="..\Meya.UI\Meya.UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="..\..\..\app\MeyaLogo.png" Link="Assets\MeyaLogo.png" />
  </ItemGroup>
</Project>
